name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry, git dependencies, and build artifacts
        uses: swatinam/cargo-cache@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run tests with nextest
        run: cargo nextest run

